name: Docker Build - ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Get Commit Hash
      id: get_commit_hash
      run: echo "::set-output name=COMMIT_HASH::$(git rev-parse --short=8 $GITHUB_SHA)"
    
    - name: Set tag on manifest
      run: |
         yq e '.image.tag = "${{ steps.get_commit_hash.outputs.COMMIT_HASH }}"' -i ./helm/my-python-app/values.yaml 

    - name: Commiting the new tag
      run: |
         git config user.name "iriscafe"
         git config user.email ${{ secrets.EMAIL }}

         git add ./helm/my-python-app/values.yaml
         git commit -m "Update image tag to ${{ steps.get_commit_hash.outputs.COMMIT_HASH }} [skip ci]"
         git remote set-url origin https://iriscafe:${{ secrets.TOKEN }}@github.com/iriscafe/desafio-devops.git
         git push --set-upstream origin master
         
    - name: Build Docker Image
      run: docker build -t iriscafe50/app_python .
  
    - name: Tag Docker Image with Commit Hash
      run: docker tag iriscafe50/app_python iriscafe50/app_python:${{ steps.get_commit_hash.outputs.COMMIT_HASH }}

    - name: Push Docker Image with Commit Hash
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push iriscafe50/app_python:${{ steps.get_commit_hash.outputs.COMMIT_HASH }}
         
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}